version: "3.8"

services:
  api:
    build:
      context: .
      target: base
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/postgres
    depends_on:
      - postgres
    command: sh -c 'pnpm i --reporter=silent && pnpm prisma-gen && pnpm migrate-dev && pnpm dev:api'
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin: